### ISSUE TITLE
What's the rationale behind this mod17 function?

### ISSUE THREAD

**Issue by lukaseder** [Microsoft/go-winio#38] opened 2017-01-12 21:41 UTC
Hi there!

Reddit is discussing your interesting [`mod17()`](https://github.com/Microsoft/go-winio/blob/v0.3.7/wim/lzx/lzx.go#L260) function. Discussion here:
https://redd.it/5nksq5

What's the rationale behind this "interesting" implementation?

Cheers,
Lukas

**Comment by gufertum** [comment] 2017-01-12 22:27
+1

**Comment by jstarks** [comment] 2017-01-12 22:30
It's not as dumb as it sounds :smiley:, but upon further investigation we should probably remove this "optimization". Basically we only expect to ever mod very small values; if I recall correctly, we will only ever go through the loop zero or one times (i.e. it could have been an `if`). The theory was that this would be faster than a naïve mod implementation, one that used a division instruction. I can't remember the inspiration for this particular choice.

Of course, go is smarter than I thought and does strength reduction on the mod 17, converting it to a multiplication and some shifts. So mod is not quite as slow as I expected.

As a result, according to some quick benchmarks I just put together, the two approaches actually are fairly close in performance, depending on how predictable the branch is (when highly predictable, the loop performs better, when less predictable, the native mod implementation performs better, as you would expect).

So we should just remove the premature optimization. Thanks for pointing this out!

**Comment by nukeop** [comment] 2017-01-13 00:06
microsoft pajeets hard at work

Reminder that Go was designed to be a langugae for Googlers too dumb to learn C. Looks like MS is using it as was intended.

**Comment by lukaseder** [comment] 2017-01-13 08:09
Thanks a lot for the explanation! :)

**Comment by darrenstahlmsft** [comment] 2017-08-02 19:08
Fixed by https://github.com/Microsoft/go-winio/pull/37

**Closed by darrenstahlmsft** 2017-08-02 19:08 UTC
